ami:
    #Image details and region
  - image-id: ami-44e5d221
  - security-group-id: sg-0c59ab67
  
instance:
    #Number of Systems/Instances on which the execution should take place
  - 1  

operatingsystem:
  - windows
  
instance-type:
  - t2.micro
  
keyname:
  - TestKeyOne
