gitUrl:
  - https://github.com/Yajan/BlazeMeterMammothScript.git

jmeterPath:
  - C:\Users\Yajana\apache-jmeter-3.3\apache-jmeter-3.3\bin

scripts:
  - chrome: C:\Users\Yajana\apache-jmeter-3.3\apache-jmeter-3.3\Scripts\Chrome
  - firefox: C:\Users\Yajana\apache-jmeter-3.3\apache-jmeter-3.3\Scripts\Firefox

reports:
  - C:\Users\Yajana\apache-jmeter-3.3\apache-jmeter-3.3\Reports