gitUrl:
  - https://github.com/Yajan/BlazeMeterMammothScript.git

jmeterPath:
  - C:\Users\Administrator\Documents\apache-jmeter-3.3\bin
scripts:
  - \Scripts\Chrome
  - \Scripts\Firefox

reports:
  - C:\Users\Administrator\Documents\Results
